415: Update docker setup and php version
itk-dev/adgangsstyring pull request #13
Opened 2024-01-09 10:01 UTC by jekuaitk

https://leantime.itkdev.dk/tickets/showKanban#/tickets/showTicket/415

* Upgrades PHP version

2024-01-09 12:26 UTC, rimi-itk requested changes

2024-01-09 12:26 UTC, rimi-itk commented on README.md
> +* Drupal: [itk-dev/azure_ad_delta_sync](https://github.com/itk-dev/azure_ad_delta_sync)
It's confusing that `https://github.com/itk-dev/azure-ad-delta-sync` (this repository) and `https://github.com/itk-dev/azure_ad_delta_sync`.

2024-01-09 12:26 UTC, rimi-itk commented on README.md
> +A `docker-compose.yml` file with a PHP 8.1 image is included in this project.
PHP 8.1 is no longer supported for real (cf. https://www.php.net/supported-versions.php).

2024-01-09 12:26 UTC, rimi-itk commented on README.md
> +docker run --interactive --tty --rm --volume ${PWD}:/app itkdev/php8.1-fpm:latest composer coding-standards-check
Use [Compose](https://docs.docker.com/compose/) for this:

```suggestion
docker compose run --rm phpfpm composer install
docker compose run --rm phpfpm composer coding-standards-check
```

2024-01-09 12:26 UTC, rimi-itk commented on docker-compose.yml
> +    image: itkdev/php8.1-fpm:latest
```suggestion
    image: itkdev/php8.2-fpm:latest
```

2024-01-09 12:26 UTC, rimi-itk commented on package.json
> +    "coding-standards-apply": "yarn coding-standards-apply/markdownlint"
🎉

2024-01-09 12:26 UTC, rimi-itk commented on tests/ControllerTest.php
> +     * Ensure the function does not call removeUsersFromDeletionList twice when there is no users on second list
```suggestion
     * Ensure the function does not call removeUsersFromDeletionList twice when there are no users on second list
```

2024-01-09 12:26 UTC, rimi-itk commented on .env
> +COMPOSE_PROJECT_NAME=azure_ad_delta_sync
Align this with the repositiory name:
```suggestion
COMPOSE_PROJECT_NAME=azure-ad-delta-sync
```

2024-01-09 12:26 UTC, rimi-itk commented on .env
> +COMPOSE_DOMAIN=azure_ad_delta_sync.local.itkdev.dk
Do we really need this? We don't have a website in this repository and hence no domain.

2024-01-09 12:39 UTC, jekuaitk commented on README.md
> +* Drupal: [itk-dev/azure_ad_delta_sync](https://github.com/itk-dev/azure_ad_delta_sync)
It is indeed. I will rename the Symfony bundle to `itk-dev/azure-ad-delta-sync-symfony` and the Drupal module to `itk-dev/azure-ad-delta-sync-drupal`.

2024-01-09 12:43 UTC, jekuaitk commented on README.md
> +A `docker-compose.yml` file with a PHP 8.1 image is included in this project.
Updated to 8.2.

2024-01-09 12:44 UTC, jekuaitk commented on README.md
> +docker run --interactive --tty --rm --volume ${PWD}:/app itkdev/php8.1-fpm:latest composer coding-standards-check
Updated.

2024-01-09 12:44 UTC, jekuaitk commented on docker-compose.yml
> +    image: itkdev/php8.1-fpm:latest
Updated.

2024-01-09 12:44 UTC, jekuaitk commented on tests/ControllerTest.php
> +     * Ensure the function does not call removeUsersFromDeletionList twice when there is no users on second list
Updated.

2024-01-09 12:45 UTC, jekuaitk commented on .env
> +COMPOSE_PROJECT_NAME=azure_ad_delta_sync
Removed.

2024-01-09 12:45 UTC, jekuaitk commented on .env
> +COMPOSE_DOMAIN=azure_ad_delta_sync.local.itkdev.dk
Nope - removed.

2024-01-12 14:25 UTC, rimi-itk approved these changes

2025-01-17 10:29 UTC, rimi-itk requested changes

2025-01-17 10:29 UTC, rimi-itk commented on docker-compose.yml
> +    image: itkdev/php8.2-fpm:latest
```suggestion
    image: itkdev/php8.3-fpm:latest
```

2025-01-17 11:34 UTC, rimi-itk approved these changes

2025-01-17 11:35 UTC, merged