Adgangsstyring package
itk-dev/adgangsstyring pull request #7
Opened 2021-08-05 09:48 UTC by jekuaitk

Composer package for acquiring users in specific Azure AD group.

2021-08-09 12:26 UTC, turegjorup requested changes
I like the test setup it helps build confidence in the package. I also like how this and the using packages are designed to work together.

But there are to many "basics" missing:
* Our team standard is docker. Even is your personal choice is different docker setup should be included
* Always use PSR interfaces when possible. Don't force a particular implementation on the using packages/systems 
* Docblocks are missing or without descriptions
* Class constants should be used whenever strings are hard coded
* Error handling (`json_decode`) could be improved
* PHP version constraints are not specified

2021-08-09 12:26 UTC, turegjorup commented on composer.json
>      "name": "itkdev/adgangsstyring",
Name should be changed to something more descriptive and in english

2021-08-09 12:26 UTC, turegjorup commented on composer.json
> +    "description": "Adgangsstyring",
This doesn't match what the readme states

2021-08-09 12:26 UTC, turegjorup commented on composer.json
> +        "ext-json": "*",
PHP version contraint missing

2021-08-09 12:26 UTC, turegjorup commented on src/Controller.php
>  use GuzzleHttp\Client;
We should not depend on Guzzle directly, but use [PSR-18](https://www.php-fig.org/psr/psr-18/). That way the using system can use any of the [implementing libraries](https://packagist.org/providers/psr/http-client-implementation) depending on preference.

2021-08-09 12:26 UTC, turegjorup commented on src/Controller.php
> +        $url = 'https://login.microsoftonline.com/' . $this->options['tenant_id'] . '/oauth2/v2.0/token';
Please use class constants for url strings

2021-08-09 12:26 UTC, turegjorup commented on src/Controller.php
> +                    'scope' => 'https://graph.microsoft.com/.default',
Please use class constants for url strings

2021-08-09 12:26 UTC, turegjorup commented on src/Controller.php
> +                    'grant_type' => 'client_credentials',
Again, use class constant to improve readability of the class. This also aids auto complete and helps prevent errors if the strings need to be used in more than one location

2021-08-09 12:26 UTC, turegjorup commented on src/Controller.php
> +        $token = json_decode($postResponse->getBody()->getContents());
Please use `JSON_THROW_ON_ERROR` as option to ensure exceptions a thrown on invalid json, then add try/catch for error handling

2021-08-09 12:26 UTC, turegjorup commented on src/Controller.php
> +        $groupUrl = 'https://graph.microsoft.com/v1.0/groups/' . $this->options['group_id'] . '/members';
Class constants again

2021-08-09 12:26 UTC, turegjorup commented on src/Controller.php
> +            throw new DataException('Cannot get users.', $e->getCode(), $e);
This is not really a `DataException` but most likely network related

2021-08-09 12:26 UTC, turegjorup commented on src/Controller.php
>          return json_decode($response->getBody()->getContents(), true);
Please use JSON_THROW_ON_ERROR as option to ensure exceptions a thrown on invalid json, then add try/catch for error handling

2021-08-09 12:26 UTC, turegjorup commented on src/Handler/HandlerInterface.php
> +     *
Docblock incomplete. Please add description. The interface is the most important part to document because this is what using systems/packages need to implement.

2021-08-09 12:26 UTC, turegjorup commented on src/Handler/HandlerInterface.php
> +    public function start(): void;
`start` is not a good name. Consider using a name that clearly conveys what is does. Suggestion: `collectUsersForDeletionList`

2021-08-09 12:26 UTC, turegjorup commented on src/Handler/HandlerInterface.php
> +    public function retainUsers(array $users): void;
Better name, but could be improved. `removeUsersFromDeletionList` ?

2021-08-09 12:26 UTC, turegjorup commented on src/Handler/HandlerInterface.php
> +    /**
Docblock incomplete. Please add description

2021-08-09 12:26 UTC, turegjorup commented on src/Handler/HandlerInterface.php
> +     *
Docblock incomplete. Please add description

2021-08-09 12:26 UTC, turegjorup commented on README.md
> +
Docker setup?

2021-08-09 12:26 UTC, turegjorup commented on src/Controller.php
> +    public function __construct(Client $client, array $options)
Docblock missing/incomplete. Goes for all functions in this class

2021-08-09 12:54 UTC, jekuaitk commented on composer.json
> +        "ext-json": "*",
Added PHP version constraint.

2021-08-09 13:19 UTC, jekuaitk commented on src/Controller.php
> +        $url = 'https://login.microsoftonline.com/' . $this->options['tenant_id'] . '/oauth2/v2.0/token';
Used class constant.

2021-08-10 06:49 UTC, jekuaitk commented on src/Controller.php
> +        $token = json_decode($postResponse->getBody()->getContents());
Added `JSON_THROW_ON_ERROR` option and surrounded with try/catch.

2021-08-10 06:49 UTC, jekuaitk commented on src/Controller.php
>          return json_decode($response->getBody()->getContents(), true);
Added `JSON_THROW_ON_ERROR` option and surrounded with try/catch.

2021-08-10 06:53 UTC, jekuaitk commented on src/Handler/HandlerInterface.php
> +    public function start(): void;
Renamed `start` to `collectUsersForDeletionList `.

2021-08-10 06:54 UTC, jekuaitk commented on src/Handler/HandlerInterface.php
> +    public function retainUsers(array $users): void;
Renamed `retainUsers` to `removeUsersFromDeletionList` and `commit` to `commitDeletionList`.

2021-08-10 07:44 UTC, jekuaitk commented on src/Handler/HandlerInterface.php
> +    /**
Added description

2021-08-10 07:44 UTC, jekuaitk commented on src/Handler/HandlerInterface.php
> +     *
Added description

2021-08-13 12:20 UTC, jekuaitk commented on src/Controller.php
> +    public function __construct(Client $client, array $options)
Added function documentation for functions in `Controller`.

2021-08-13 12:25 UTC, jekuaitk commented on src/Handler/HandlerInterface.php
> +     *
Added Docblock to the `HandlerInterface`.

2021-08-13 12:26 UTC, jekuaitk commented on composer.json
> +    "description": "Adgangsstyring",
Updated description in both the `README.md` and `composer.json`.

2021-08-16 08:42 UTC, jekuaitk commented on src/Controller.php
> +            throw new DataException('Cannot get users.', $e->getCode(), $e);
Throwing new `NetworkException` class instead of `DataException`.

2021-08-17 08:51 UTC, jekuaitk commented on src/Controller.php
>  use GuzzleHttp\Client;
Using PSR-18 rather than Guzzle directly. Using [Nyholm\Psr7\Request](https://github.com/Nyholm/psr7) as we need some sort of `RequestInterface` implementation.

2021-08-17 10:57 UTC, jekuaitk commented on README.md
> +
Added Docker setup.

2021-08-17 10:58 UTC, jekuaitk commented on composer.json
>      "name": "itkdev/adgangsstyring",
Renamed to `itk-dev/azure-ad-delta-sync`.

2021-08-18 11:30 UTC, turegjorup approved these changes
One minor comment

2021-08-18 11:30 UTC, turegjorup commented on .github/workflows/pr.yaml
> +          extensions: ctype, dom, iconv, json, zip, gd, soap
Don't think we need `soap`, `gd`, `dom`, `zip`

2021-08-18 11:30 UTC, turegjorup commented on .github/workflows/pr.yaml
> +          extensions: ctype, dom, iconv, json, zip, gd, soap
Extentions again

2021-08-18 11:30 UTC, turegjorup commented on README.md
> +composer require itkdev/adgangsstyring
Package rename

2021-08-18 11:30 UTC, turegjorup commented on composer.json
> +        "escapestudios/symfony2-coding-standard": "^3.12",
This should only be a `dev` dependency

2021-08-18 11:55 UTC, merged